env:
  browser: true
  commonjs: true
  node: true
extends: 'eslint:recommended'
globals:
  beforeEach: false
  define: false
  describe: false
  expect: false
  it: false
  jasmine: false
parserOptions:
  ecmaVersion: 5
ignorePatterns:
  - 'coverage/**'
  - 'dist/**'
  - '**/*.ts'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
    - allow:
      - error
